apiVersion: v1
kind: Service

metadata:
  name: time-tracker
  namespace: diplom

spec:
  type: NodePort
  selector:
    app: time-tracker
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
