global:
  scrape_interval: '10s'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'prometheus:9090'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - 'cadvisor:8080'


  - job_name: 'blackbox-time-tracker'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - 'http://host.docker.internal:30080/'
    relabel_configs:
      - target_label: __param_target
        source_labels: [__address__]
      - target_label: instance
        source_labels: [__param_target]
      - target_label: __address__
        replacement: blackbox:9115
